name: API Pipeline

on:
  push:
    paths:
      - "orchestrator/**"
      - ".github/workflows/api.yml"

permissions:
  contents: read
  packages: write

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: pip install uv

      - working-directory: orchestrator
        run: uv sync

      - working-directory: orchestrator
        run: uv run ruff check .

      - working-directory: orchestrator
        run: uv run mypy .

      - working-directory: orchestrator
        run: uv run pytest

  docker:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build imagem
        run: docker build -f orchestrator/dockerfile -t ghcr.io/douglas-chash-test/contabot-api:latest orchestrator

      - name: Push imagem
        run: docker push ghcr.io/douglas-chash-test/contabot-api:latest
